# -*- coding: utf-8 -*-
"""data_cleaning_process.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ds2Y1E4eoksAHVYpxfS-kRHWu478fzW
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('hotel_booking.csv')

# Basic Info
print("Shape of dataset:", df.shape)
print("\nData types:\n", df.dtypes)
print("\nFirst 5 rows:\n", df.head())
print("\nLast 5 rows:\n", df.tail())
print("\nStatistical Summary:\n", df.describe(include='all'))

# Total missing values
missing = df.isnull().sum()
percent = (missing / len(df)) * 100
missing_df = pd.DataFrame({'Missing Values': missing, 'Percent': percent})
print(missing_df[missing_df['Missing Values'] > 0])

# Visualize missing data
sns.heatmap(df.isnull(), cbar=False, yticklabels=False)
plt.title("Missing Values Heatmap")
plt.show()

# Children column: replace NaN with 0
df['children'].fillna(0, inplace=True)

# Country column: replace NaN with mode
df['country'].fillna(df['country'].mode()[0], inplace=True)

# Agent column: replace NaN with 0
df['agent'].fillna(0, inplace=True)

# Company column: replace NaN with 0
df['company'].fillna(0, inplace=True)

# Check duplicates
duplicates = df.duplicated()
print("Number of exact duplicates:", duplicates.sum())

# Remove duplicates
df = df.drop_duplicates()

for col in ['lead_time', 'adr', 'adults', 'children', 'babies']:
    sns.boxplot(x=df[col])
    plt.title(f'Boxplot of {col}')
    plt.show()

Q1 = df['adr'].quantile(0.25)
Q3 = df['adr'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

# Remove outliers
df = df[(df['adr'] >= lower) & (df['adr'] <= upper)]

# Remove rows with 0 adults, children, and babies
df = df[~((df['adults'] == 0) & (df['children'] == 0) & (df['babies'] == 0))]

df['total_guests'] = df['adults'] + df['children'] + df['babies']
print("Guests <= 0:", df[df['total_guests'] <= 0].shape[0])

df.to_csv('hotel_bookings_cleaned.csv', index=False)